events {}

http {
    server {
        listen 8080;

        location /service1/ {
            proxy_pass http://go_app:8001/;
        }

        location /service2/ {
            proxy_pass http://python_app:8002/;
        }
    }
}
